services:
  - type: web
    name: complai-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8080
